



spring:
  application:
    name: CONNECT
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CONNECT_DATA
  redis:
    host: localhost
    port: 6379



server:
  port: 8080


weather:
  api:
    key: e44f51fd9b1ce0fbd4f5bd9a1d81e057


logging:
  level:
    net:
      connect:
        Connect: DEBUG

# 1. ERROR
# 2. WARN
# 3. INFO
# 4. DEBUG
# 5. TRACE