



spring:
  application:
    name: CONNECT
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CONNECT_DATA



server:
  port: 8080


logging:
  level:
    net:
      connect:
        Connect: DEBUG

# 1. ERROR
# 2. WARN
# 3. INFO
# 4. DEBUG
# 5. TRACE